### ISSUE TITLE
JavaScriptdən bu məsələləri işləməyə çalışın

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [elvintj/Foundation-Pragmatech-Project#23]
**[Bu](https://www.w3resource.com/javascript-exercises/javascript-basic-exercises.php)** linkdə 150 dənə çox da çətin olmayan Javascript məsələləri var. Boş vaxtlarınızda işləyə bilərsiniz.

**Comment by elvintj** [comment]
Çox sağolun

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Nəzrin İsbəndiyarova ***@***.***>
Sent: Monday, December 20, 2021 10:00:36 PM
To: elvintj/Foundation-Pragmatech-Project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elvintj/Foundation-Pragmatech-Project] JavaScriptdən bu məsələləri işləməyə çalışın (Issue #23)


Bu<https://www.w3resource.com/javascript-exercises/javascript-basic-exercises.php> linkdə 150 dənə çox da çətin olmayan Javascript məsələləri var. Boş vaxtlarınızda işləyə bilərsiniz.
